overrides:
  hwpe-stream:          { git: "git@code.ihep.ac.cn:heris/heris-platform/hwpe-stream.git",          version: 1.9.1 }
  udma_uart:            { git: "git@code.ihep.ac.cn:heris/heris-platform/udma_uart.git",            version: 2.0.0 }
  generic_fll:          { git: "git@code.ihep.ac.cn:heris/heris-platform/generic_FLL.git",          version: 0.2.0 }
  fpnew:                { git: "git@code.ihep.ac.cn:heris/heris-platform/cvfpu.git",                rev: "a8e0cba6dd50f357ece73c2c955d96efc3c6c315" }
  hwpe-mac-engine:      { git: "git@code.ihep.ac.cn:heris/heris-platform/hwpe-mac-engine.git",      version: 1.3.3 }
  udma_filter:          { git: "git@code.ihep.ac.cn:heris/heris-platform/udma_filter.git",          version: 2.0.0 }
  common_verification:  { git: "git@code.ihep.ac.cn:heris/heris-platform/common_verification.git",  version: 0.2.5 }
  cluster_interconnect: { git: "git@code.ihep.ac.cn:heris/heris-platform/cluster_interconnect.git", version: 1.3.0 }
  udma_camera:          { git: "git@code.ihep.ac.cn:heris/heris-platform/udma_camera.git",          version: 2.0.0 }
  udma_core:            { git: "git@code.ihep.ac.cn:heris/heris-platform/udma_core.git",            version: 2.0.0 }
  udma_i2c:             { git: "git@code.ihep.ac.cn:heris/heris-platform/udma_i2c.git",             version: 3.0.0 }
  cv32e40p:             { git: "git@code.ihep.ac.cn:heris/heris-platform/cv32e40p.git",             rev: "7a49867b2232d97344cde1b8a1e05bcb38634894" }
  adv_dbg_if:           { git: "git@code.ihep.ac.cn:heris/heris-platform/adv_dbg_if.git",           version: 2.0.2 }
  udma_hyper:           { git: "git@code.ihep.ac.cn:heris/heris-platform/udma_hyper.git",           version: 0.1.0 }
  ibex:                 { git: "git@code.ihep.ac.cn:heris/heris-platform/ibex.git",                 rev: "b18f7ef178ed07f5085051f96042c670a919fd5c" }
  apb2per:              { git: "git@code.ihep.ac.cn:heris/heris-platform/apb2per.git",              version: 0.1.0 }
  apb_adv_timer:        { git: "git@code.ihep.ac.cn:heris/heris-platform/apb_adv_timer.git",        version: 1.0.4 }
  scm:                  { git: "git@code.ihep.ac.cn:heris/heris-platform/scm.git",                  version: 1.2.0 }
  udma_sdio:            { git: "git@code.ihep.ac.cn:heris/heris-platform/udma_sdio.git",            version: 2.0.0 }
  fpu_div_sqrt_mvp:     { git: "git@code.ihep.ac.cn:heris/heris-platform/fpu_div_sqrt_mvp.git",     version: 1.0.4 }
  pulp_io:              { git: "git@code.ihep.ac.cn:heris/heris-platform/pulp-io.git",              version: 0.1.0 }
  hwpe-ctrl:            { git: "git@code.ihep.ac.cn:heris/heris-platform/hwpe-ctrl.git",            version: 1.7.3 }
  timer_unit:           { git: "git@code.ihep.ac.cn:heris/heris-platform/timer_unit.git",           version: 1.0.3 }
  gpio:                 { path: "hw/vendored_ips/gpio"                                             }
  udma_i2s:             { git: "git@code.ihep.ac.cn:heris/heris-platform/udma_i2s.git",             version: 2.0.0 }
  riscv-dbg:            { git: "git@code.ihep.ac.cn:heris/heris-platform/riscv-dbg.git",            version: 0.5.1 }
  axi:                  { git: "git@code.ihep.ac.cn:heris/heris-platform/axi.git",                  version: 0.39.8 }
  apb_interrupt_cntrl:  { git: "git@code.ihep.ac.cn:heris/heris-platform/apb_interrupt_cntrl.git",  version: 0.2.0 }
  udma_qspi:            { git: "git@code.ihep.ac.cn:heris/heris-platform/udma_qspi.git",            version: 2.0.0 }